name: DAST Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.8.0

      - name: Use Docker Compose Action
        uses: docker/compose-action@v2.0.0
        with:
          run: up -d

      - name: Verify Docker containers
        run: docker ps


      - name: Start application
        run: |
          docker-compose up -d # ali ukaz za zagon aplikacije



